--wtf retarded shit
usermessage.Hook("EmitSound",function (um)
	um:ReadEntity():EmitSound(um:ReadString())
end)
usermessage.Hook("EmitSound2",function (um)
	um:ReadEntity():EmitSound(um:ReadString(),um:ReadFloat())
end)
usermessage.Hook("EmitSound3",function (um)
	um:ReadEntity():EmitSound(um:ReadString(),um:ReadFloat(),um:ReadFloat())
end)

usermessage.Hook("WorldSound",function (um)
	WorldSound(um:ReadString(),um:ReadVector())
end)
usermessage.Hook("WorldSound2",function (um)
	WorldSound(um:ReadString(),um:ReadVector(),um:ReadShort())
end)
usermessage.Hook("WorldSound3",function (um)
	WorldSound(um:ReadString(),um:ReadVector(),um:ReadShort(),um:ReadShort())
end)